#!/bin/bash

program=$0
if [[ $# != 2 ]]
then
	echo "Usage:  $program source destination"
	echo " e.g.,  $program bad_4dfp_name better_4dfp_name"
	echo "N.B.:   $program works only with 4dfp files; it does not work on directories"
	exit 1
fi
program=`basename $program`
src=$1
dest=$2
bsrc=`basename $src`
bdest=`basename $dest`

if [[ ! -e ${src}.4dfp.img || ! -e ${src}.4dfp.ifh || ! -e ${src}.4dfp.hdr ]]; then
    echo "$program could not find 4dfp-files for $src"
    exit 1
else
	echo "$program will copy $src to $dest"
fi

cp -f ${src}.4dfp.img ${dest}.4dfp.img
if [[ -e ${dest}.4dfp.ifh ]]; then
	rm -f ${dest}.4dfp.ifh
fi
sed ''s/${bsrc}/${bdest}/g'' ${src}.4dfp.ifh > ${dest}.4dfp.ifh
cp -f ${src}.4dfp.hdr ${dest}.4dfp.hdr
if [[ -e ${dest}.4dfp.img.rec ]]; then
	rm -f ${dest}.4dfp.img.rec
fi
echo "rec ${dest}.4dfp.img `date` `whoami`" >> ${dest}.4dfp.img.rec
echo $program $1 $2                         >> ${dest}.4dfp.img.rec
cat  ${src}.4dfp.img.rec                    >> ${dest}.4dfp.img.rec
echo "endrec `date` jjlee"                  >> ${dest}.4dfp.img.rec
